const { app, BrowserWindow, Tray, Menu, ipcMain } = require('electron');
const { setupTitlebar, attachTitlebarToWindow } = require('custom-electron-titlebar/main');
const path = require('path');
const fs = require('fs');
const fsp = require('fs').promises;

const webserver = require('./webserver');

// ugly hack to remove menu generated by custom-electron-titlebar
/* const menu = new Menu();
Menu.setApplicationMenu(menu); */

setupTitlebar();

function createWindow() {
    mainWindow = new BrowserWindow({
        width: 800,
        height: 350,
        titleBarStyle: 'hidden',
        resizable: false,
        webPreferences: {
            preload: path.join(__dirname, 'preload.js'),
            contextIsolation: true,
            sandbox: false,
        }
    });

    // Load the GUI HTML file
    mainWindow.loadFile(path.join(__dirname, 'frontend', 'gui.html'));

    // Create the Tray instance
    const iconPath = path.join(__dirname, 'build', 'icons', 'icon.png');
    let tray = new Tray(iconPath);
    const contextMenu = Menu.buildFromTemplate([
        {
            label: 'Open', click: function () {
                mainWindow.show()
            }
        },
        {
            label: 'Quit', click: function () {
                app.quit()
            }
        }
    ])

    tray.setToolTip('Your App Name')
    tray.setContextMenu(contextMenu)

    // Minimize mainWindow to the system tray
    mainWindow.on('minimize', function (event) {
        event.preventDefault()
        mainWindow.hide()
    })

    // Show the mainWindow when the tray icon is clicked
    tray.on('click', function () {
        mainWindow.show()
    })

    mainWindow.webContents.on('did-finish-load', () => {
        mainWindow.on('close', (event) => {
            event.preventDefault();
            mainWindow.webContents.send('close-save-data');
        });
    
        ipcMain.on('close-save-data-response', () => {
            mainWindow.destroy(); // Now close the window
        });
    });

    // Nullify mainWindow when the window is closed.
    mainWindow.on('closed', () => {
        mainWindow = null;
    });

    attachTitlebarToWindow(mainWindow);
}

async function readLastPlayed() {
    const filePath = path.join(__dirname, 'userData', 'lastPlayed.json');
    try {
        const data = await fsp.readFile(filePath, 'utf8');
        if (data.trim()) {
            const lastPlayed = JSON.parse(data);
            mainWindow.webContents.send('load-data', lastPlayed);
        } else {
            console.log('lastPlayed.json is empty, no data sent.');
        }
    } catch (err) {
        console.log('Error reading lastPlayed.json:', err);
    }
}

function saveLastPlayed(data) {
    const filePath = path.join(__dirname, 'userData', 'lastPlayed.json');
    fs.writeFile(filePath, JSON.stringify(data, null, 2), 'utf8', (err) => {
        if (err) {
            console.log('Error saving lastPlayed.json:', err);
        } else {
            console.log('Data saved successfully!');
        }
    });
}

// When app is ready, open the window
app.whenReady().then(() => {
    createWindow();

    fs.readFile(path.join(__dirname, 'userData', 'lastPlayed.json'), 'utf8', (err, data) => {
        if (err) {
            console.log('Error reading lastPlayed.json:', err);
            return;
        }
        readLastPlayed();
    });
});

// Quit when all windows are closed, except on macOS
app.on('window-all-closed', function () {
    if (process.platform !== 'darwin') app.quit()
});

app.on('activate', function () {
    if (BrowserWindow.getAllWindows().length === 0) createWindow()
});

ipcMain.on('start-server', (event, data) => {
    webserver.startServer(data);
    mainWindow.webContents.send('server-status', true); // Notify renderer the server has started
});

ipcMain.on('stop-server', () => {
    webserver.stopServer();
    mainWindow.webContents.send('server-status', false); // Notify renderer the server has stopped
    mainWindow.webContents.send('save-data');
});

ipcMain.on('save-data-response', (event, data) => {
    saveLastPlayed(data);
});