name: "Auto Close PRs"

on: [pull_request]

jobs:
  close_pr:
    runs-on: ubuntu-latest
    steps:
    - name: Close Pull Request
      uses: peter-evans/close-pull-request@v1
      with:
        comment: "Pull requests are not accepted on this repository."
